apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
spec:
  serviceAccount:
    annotations:
      "eks.amazonaws.com/role-arn": "{{.Values.roleArn}}"
  client:
    preferService: true
  ingress:
    enabled: False
    pathType: Prefix
    path: "/"
  config:
    log:
      mode: "console"
      level: "error"
    log.frontend:
      enabled: true
    auth:
#      disable_login_form: Falseyes
#      disable_signout_menu: "True"
      sigv4_auth_enabled: true
    auth.anonymous:
      enabled: False
  service:
    name: "grafana-service"
    labels:
      app: "grafana"
      type: "grafana-service"
    type: NodePort
  dashboardLabelSelector:
    - matchExpressions:
        - { key: app, operator: In, values: [grafana] }
  resources:
    # Optionally specify container resources
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 30m
      memory: 100Mi