# This is a basic workflow to help you get started with Actions

name: APPLY_DEV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo
    steps:
      - uses: actions/checkout@v3

      - name: AWS cli install action
        uses: chrislennon/action-aws-cli@1.1

      - name: Configure AWS Credentials
        uses: ./.github/actions/login-dev

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_wrapper: false
          terraform_version: 1.1.9

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v2.1
        with:
          version: 'v1.24.2'

      - name: Install python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.1
        with:
          terragrunt_version: 0.36.6

      - name: Terragrunt apply
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 1
          shell: bash
          command: |
            cd terragrunt/dev
            terragrunt run-all apply --terragrunt-non-interactive --terragrunt-include-external-dependencies